#!/usr/bin/env python

import sys
import subprocess
from container import Container

if __name__ == '__main__':
    cmd = 'docker ps -a'
    out = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE).stdout.read()
    containers = out.split('\n')
    title = containers[0]
    names_offset = title.index('NAMES')
    cs = [ c[names_offset:] for c in containers[1:] if c]
    cs.sort()
    for c in cs:
        print(c)
