#!/usr/bin/env python

import utils
import sys
import getopt
from container import Container

if __name__ == '__main__':
    optlist, _ = getopt.getopt(sys.argv[1:], 'ac:')
    options = dict(optlist)
    column = options.get('-c', 'NAMES')
    for c in utils.docker_ps(list_all='-a' in options, column=column):
        print(c)
