#!/usr/bin/env python

import sys
import utils

if __name__ == '__main__':
    networks = sys.argv[1:]
    if not networks:
        print('usage:freeipof network')
        sys.exit(1)
    for network in networks:
        for ip in utils.free_ip_list_of(network):
            print(ip)

