#!/usr/bin/env python

import sys
from container import Container

if __name__ == '__main__':
    containers = sys.argv[1:]
    if not containers:
        print('usage:ipof containers')
        sys.exit(1)
    for c in containers:
        container = Container(c)
        ips = container.ip()
        print('none' if not ips else ','.join(ips))

