#!/usr/bin/env python

import sys
from container import Container

if __name__ == '__main__':
    containers = sys.argv[1:]
    if len(containers) != 1:
        print('usage:ipof container')
        sys.exit(1)
    container = Container(containers[0])
    ips = container.ip()
    for ip in ips:
        os.system('calicoctl ipam release --ip={ip}'.format(ip=ip))
    os.system('docker start {container}'.format(container=containers[0]))

