#!/usr/bin/env python

import sys
import os
from container import Container

if __name__ == '__main__':
    containers = sys.argv[1:]
    if len(containers) != 1:
        print('usage:ipof container')
        sys.exit(1)
    container = Container(containers[0])
    ips = container.ip()
    for ip in ips:
        cmd = 'calicoctl ipam release --ip={ip}'.format(ip=ip)
        print(cmd)
        os.system(cmd)
    cmd = 'docker start {container}'.format(container=containers[0])
    print(cmd)
    os.system(cmd)

