#!/usr/bin/env python

import sys
import os
import utils

if __name__ == '__main__':
    images = """docker images | awk '{print $1}'"""
    images = utils.exec_cmd(images).split('\n')[1:]
    for image in images:
        if image:
            cmd = 'docker save {image} | ssh {remote} "docker load"'
            for host in sys.argv[1:]:
                c = cmd.format(image=image, remote=host)
                print(c)
                #os.system(c)
