#!/usr/bin/env python

import sys
import getopt
import os

if __name__ == '__main__':
    cmd = 'docker save {image} | ssh {remote} "docker load"'
    optlist, hosts = getopt.getopt(sys.argv[1:], '-i:', [])
    options = dict(optlist)
    image = options.get('-i')
    if not image or not hosts:
        print('usage: sync_images -i IMAGE hosts')
        sys.exit(1)
    for host in hosts:
        c = cmd.format(image=image, remote=host)
        os.system(c)
