#!/usr/bin/env python
import sys
import os
import getopt

from docker_cmd import DockerCmd
import utils


class BackendCmd(DockerCmd):
    def __init__(self, node_id):
        DockerCmd.__init__(self)
        name = 'bg{gid}p{pid}'.format(gid=os.getenv("GROUP_ID"), pid=node_id)
        self.use_image('yunxuetang/maxwell_backend'). \
            daemon_mode(True). \
            copy_os_env('ZOOKEEPER', utils.zk_env()). \
            copy_os_env('GROUP_ID', can_ignore=False). \
            with_name(name). \
            with_network('maxwell'). \
            with_mount_from_env('DATA_DIR', '/app/data'). \
            with_mount_from_env('LOG_DIR', '/app/log'). \
            with_env('PARTITION_ID', node_id)


def usage():
    print('''usage:deploy-backend hosts
env: ZOOKEEPER
     GROUP_ID
     DATA_DIR
     LOG_DIR
     NAME_PREFIX default nil''')


if __name__ == "__main__":
    optlist, hosts = getopt.getopt(sys.argv[1:], 'n:', ['dryrun'])
    if not hosts:
        usage()
        sys.exit(1)
    options = dict(optlist)
    free_ip_list = utils.free_ip_list_of('maxwell')
    id_offset = int(options.get('-n', '0'))
    for index, host in enumerate(hosts):
        dryrun = '--dryrun' in dict(optlist).keys()
        BackendCmd(index+id_offset).\
            exec_in(host). \
            with_network('maxwell', ip=free_ip_list.send(None)). \
            run(dryrun=dryrun)
