#!/usr/bin/env python
import sys
import os
from getopt import getopt
import docker_cmd
import utils


class ZkCommand(docker_cmd.DockerCmd):
    def __init__(self, hosts, index):
        docker_cmd.DockerCmd.__init__(self)
        myid = index + 1
        self.name = self.instance_name(myid)
        conf = ' '.join(self.server_conf_list(hosts))
        ip = utils.ip_of('zookeeper', index)
        self.use_image('zookeeper:3.4.9'). \
            daemon_mode(). \
            with_network(network='zookeeper', ip=ip). \
            with_env('ZOO_MY_ID', myid). \
            with_env('ZOO_SERVERS', conf). \
            with_mount_from_env('DATA_DIR', '/data'). \
            with_mount_from_env('DATA_LOG_DIR', '/datalog')

    @classmethod
    def instance_name(cls, index):
        base_name = 'zk{index}'.format(index=index)
        prefix = os.getenv('NAME_PREFIX')
        return base_name if not prefix else prefix + base_name

    @classmethod
    def server_conf_list(cls, hosts):
        server_fmt = 'server.{index}={instance}:2888:3888'
        for idx, _ in enumerate(hosts):
            instance_id = idx + 1
            yield server_fmt.format(
                index=instance_id,
                instance=cls.instance_name(instance_id))


def usage():
    print('''usage:./deploy-zookeeper [--dryrun] hosts
env: DATA_DIR     : -v ${DATA_DIR}/{instance}:/data
     DATA_LOG_DIR : -v ${DATA_LOG_DIR}/{instance}:/datalog
     IP_OFFSET    : --ip 192.0.2.{IP_OFFSET+index}
     NAME_PREFIX  : --name ${NAME_PREFIX}zk{index}
     ''')


if __name__ == '__main__':
    optlist, deploy_hosts = getopt(sys.argv[1:], '', ['dryrun'])
    if not deploy_hosts:
        usage()
        sys.exit(1)
    options = dict(optlist)
    for idx, host in enumerate(deploy_hosts):
        ZkCommand(deploy_hosts, idx).exec_in(host).run('--dryrun' in options)
